### PR TITLE
Ftp with ssl

### PR DESCRIPTION
**Pull request by brownkm5**

### CODE REVIEW

**Review by jeffdill2 — CHANGES_REQUESTED** [review]
Need to update the version number.

**Comment by brownkm5** [comment]
@jeffdill2 I don't think this is a breaking change, so how about `5.1.0`?

**Comment by jeffdill2** [comment]
You'd go with 5.0.2 since this is just maintenance, not a feature.

**Comment by brownkm5** [comment]
Ah, ok

**Review by jeffdill2 — APPROVED** [review]
Don't forget to create a release after it's merged.

**Comment by brownkm5** [comment]
@jeffdill2 
pnzJTq3

**Comment by brownkm5** [comment]
For RubyGems?

**Comment by jeffdill2** [comment]
For GitHub. Go to release, click Draft New Release, and just follow the pattern of previous releases.

**Comment by brownkm5** [comment]
Ah, I see 👍

**Pull request merged**
